import { Location } from "../types";

export const LOCATIONS: Location[] = [
  Location.BLOQUE_1,
  Location.BLOQUE_2,
  Location.BLOQUE_3,
  Location.BLOQUE_4,
  Location.BLOQUE_5,
  Location.BLOQUE_6,
  Location.BLOQUE_7,
  Location.BLOQUE_8,
  Location.BLOQUE_9,
  Location.BLOQUE_10,
  Location.BLOQUE_11,
  Location.BLOQUE_12,
  Location.BLOQUE_13,
  Location.BLOQUE_14,
  Location.BLOQUE_15,
  Location.BLOQUE_16,
  Location.BLOQUE_17,
  Location.BLOQUE_18,
  Location.BLOQUE_19,
  Location.BLOQUE_20,
  Location.BLOQUE_21,
  Location.BLOQUE_22,
  Location.BLOQUE_23,
  Location.BLOQUE_24,
  Location.BLOQUE_25,
  Location.BLOQUE_26,
  Location.BLOQUE_27,
  Location.BLOQUE_28,
  Location.BLOQUE_29,
  Location.OTRO
]; 